In [1]:
import torch
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [2]:
print(x.reshape(3,4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [3]:
print(x.numel())

12


In [4]:
print(x.shape)

torch.Size([12])


In [5]:
x= x.reshape(3,4)
print(x.shape)

torch.Size([3, 4])


In [6]:
import torch
y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]]) # 二维tensor
z = torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]) # 三维tensor
print(y)
print(z)

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])
tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])


In [7]:
import torch
y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]]) # 二维tensor
z = torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]) # 三维tensor
print(y.shape)
print(z.shape)

torch.Size([3, 4])
torch.Size([1, 3, 4])


In [8]:
x = torch.tensor([1.0,2,4,8]) 
y = torch.tensor([2,2,2,2]) 
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y) # **运算符是求幂运算

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])


In [9]:
x = torch.arange(12,dtype=torch.float).reshape(3, 4)
y = torch.zeros(12).reshape(3, 4)
n = torch.cat((x,y),dim=0)
m = torch.cat((x,y), dim=1)
print(n)
print(m)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]])
tensor([[ 0.,  1.,  2.,  3.,  0.,  0.,  0.,  0.],
        [ 4.,  5.,  6.,  7.,  0.,  0.,  0.,  0.],
        [ 8.,  9., 10., 11.,  0.,  0.,  0.,  0.]])


In [10]:
x == y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [11]:
x.sum()

tensor(66.)

In [12]:
y.sum()

tensor(0.)

In [13]:
import torch
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a)
print(b)
print(a+b) # a会复制出一个3*2的矩阵，b复制出一个3*2的矩阵，然后再相加，会得到一个3*2矩阵  

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [14]:
print(x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [15]:
print(x[-1])
print(x[1:3])

tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [16]:
print(x[1,9])

IndexError: index 9 is out of bounds for dimension 1 with size 4

In [17]:
print(x[1,3])

tensor(7.)


In [18]:
import torch
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
before = id(y) 
y = x + y
print(id(y) == before) # 运行操作后，赋值后的y的id和原来的id不一样   

False


In [19]:
import torch
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
z = torch.zeros_like(y) # z 的数据类型、尺寸和y一样，里面的元素全为0
print("id(z):",id(z))    
z[:] = x + y
print("id(z):",id(z))  

id(z): 2189424073840
id(z): 2189424073840


In [36]:
#如果在后续计算中没有重复使用X，即内存不会过多复制，也可以使用X[:] = X + Y 或 X += Y 来减少操作的内存开销。
import torch
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
before = id(x) 
x += y
print(id(x) == before)   

True


In [22]:
print(type(x))

<class 'torch.Tensor'>


In [37]:
import numpy as np
print(type(x.numpy()))

<class 'numpy.ndarray'>


In [38]:
print(x)

tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]])


In [39]:
x.numpy()

array([[ 2.,  2.,  6.,  6.],
       [ 5.,  7.,  9., 11.],
       [12., 12., 12., 12.]], dtype=float32)

In [40]:
print(x)

tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]])


In [41]:
print(type(x))

<class 'torch.Tensor'>


In [42]:
x = x.numpy()

In [43]:
print(type(x))
print(x)

<class 'numpy.ndarray'>
[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]


In [44]:
x

array([[ 2.,  2.,  6.,  6.],
       [ 5.,  7.,  9., 11.],
       [12., 12., 12., 12.]], dtype=float32)

In [67]:
import os
os.makedirs(os.path.join('.','01_Data'), exist_ok=True)
data_file = os.path.join(os.path.join('.','01_Data','01_house_tiny.csv'))
print(data_file)
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

.\01_Data\01_house_tiny.csv


In [68]:
import pandas as pd
import os

data = pd.read_csv(data_file)
print(data)


   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [87]:
inputs, outputs = data.iloc[:,0:2], data.iloc[:,2]
# 处理数值型数据：对数值列用均值填充NaN
numeric_columns = inputs.select_dtypes(include=[ 'float64', 'int64'])
print(numeric_columns.columns)
inputs[numeric_columns.columns] = numeric_columns.fillna(numeric_columns.mean())

print(inputs)

Index(['NumRooms'], dtype='object')
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [94]:
inputs = pd.get_dummies(inputs) # 
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0         1.0        0.0
1       2.0         0.0        1.0
2       4.0         0.0        1.0
3       3.0         0.0        1.0


In [95]:
x, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
print(x)
print(y)

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)
tensor([127500, 106000, 178100, 140000])


In [100]:
import pandas as pd

data = {
    'color': ['red', 'blue', 'green', 'blue'],
    'size': ['S', 'M', 'L', 'S']
}
df = pd.DataFrame(data)
# 对分类数据进行独热编码
dummies = pd.get_dummies(df)


In [103]:
df

color size
0    red    S
1   blue    M
2  green    L
3   blue    S

In [102]:
dummies

color_blue  color_green  color_red  size_L  size_M  size_S
0       False        False       True   False   False    True
1        True        False      False   False    True   False
2       False         True      False    True   False   False
3        True        False      False   False   False    True