In [1]:
import numpy as np

# 创建一个3维数组，形状为 (2, 3, 4)
array = np.array([[[ 1,  2,  3,  4],
                   [ 5,  6,  7,  8],
                   [ 9, 10, 11, 12]],
                  
                  [[13, 14, 15, 16],
                   [17, 18, 19, 20],
                   [21, 22, 23, 24]]])

# 沿着轴0求和 (将两个2x3x4的矩阵相加，变为一个2x3x4的矩阵)
sum_axis0 = np.sum(array, axis=0)
print("沿轴0求和结果:\n", sum_axis0)

# 沿着轴1求和 (将每个2x3x4中的3x4矩阵的行相加，变为2x4)
sum_axis1 = np.sum(array, axis=1)
print("沿轴1求和结果:\n", sum_axis1)

# 沿着轴2求和 (将每个2x3x4中的3x4矩阵的列相加，变为2x3)
sum_axis2 = np.sum(array, axis=2)
print("沿轴2求和结果:\n", sum_axis2)

# 对整个数组求和，得到一个数值
total_sum = np.sum(array)
print("总求和结果:", total_sum)


沿轴0求和结果:
 [[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
沿轴1求和结果:
 [[15 18 21 24]
 [51 54 57 60]]
沿轴2求和结果:
 [[10 26 42]
 [58 74 90]]
总求和结果: 300


In [2]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
sum_A = A.sum(axis=1,keepdims=True) # keepdims=True不丢掉维度，否则三维矩阵按一个维度求和就会变为二维矩阵，二维矩阵若按一个维度求和就会变为一维向量
print(sum_A)
print(sum_A.shape) # 维度没有丢失，方便使用广播

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
torch.Size([5, 1])


In [3]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
sum_A = A.sum(axis=1,keepdims=True) # keepdims=True不丢掉维度，否则三维矩阵按一个维度求和就会变为二维矩阵，二维矩阵若按一个维度求和就会变为一维向量
print(A/sum_A) 

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])


In [4]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A.cumsum(axis=0)) 

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [5]:
import torch
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
print(x)
print(y)
print(torch.dot(x,y))

tensor([0., 1., 2., 3.])
tensor([1., 1., 1., 1.])
tensor(6.)


In [7]:
# 点积是相同位置的按元素成绩的和。
import torch
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
print(x)
print(y)
print(torch.sum(x*y))

tensor([0., 1., 2., 3.])
tensor([1., 1., 1., 1.])
tensor(6.)


In [8]:
# 可以通过执行按元素乘法，然后进行求和来表示两个向量的点积。
import torch
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
print(torch.sum(x*y))


tensor(6.)


In [10]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
x = torch.arange(4,dtype=torch.float32)
print(A.shape)
print(x.shape)
print(torch.mv(A,x))

torch.Size([5, 4])
torch.Size([4])
tensor([ 14.,  38.,  62.,  86., 110.])


In [11]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = torch.ones(4,3)
print(A)
print(B)
print(torch.mm(A,B))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])


In [12]:
import torch
u = torch.tensor([3.0,-4.0])
print(torch.norm(u))


tensor(5.)


In [13]:
import torch
u = torch.tensor([3.0,-4.0])
print(torch.abs(u).sum())

tensor(7.)


In [ ]:

import torch
print(torch.norm(torch.ones((4,9)))) # 把矩阵拉成一个向量，然后再求和